local M = {}

function M.setup(colors, themeConfig)
	local c = colors

	return {
		ColorColumn = { bg = c.base02 },
		Conceal = { bg = c.base01 },
		-- Cursor       { },
		-- lCursor      { },
		-- CursorIM     { },
		-- CursorColumn { },
		CursorLine = { bg = c.base02 },
		Directory = { fg = c.base10, bold = true },
		DiffAdd = { bg = c.base02, fg = c.green700 },
		DiffChange = { bg = c.base02, fg = c.yellow500 },
		DiffDelete = { bg = c.base02, fg = c.red500 },
		-- DiffText     { },
		-- EndOfBuffer  { },
		-- TermCursor   { },
		-- TermCursorNC { },
		ErrorMsg = { bg = c.red500, fg = c.base01, bold = true },
		-- VertSplit    { },
		-- Folded       { },
		-- FoldColumn   { },
		-- SignColumn   { },
		-- IncSearch    { },
		-- Substitute   { },
		LineNr = { fg = c.base04 },
		CursorLineNr = { fg = c.base10 },
		MatchParen = { bg = c.yellow500, fg = c.base03 },
		ModeMs = { fg = c.base10, bold = true },
		MsgArea = { bg = c.base01 },
		-- MsgSeparator { },
		-- MoreMsg      { },
		NonText = { fg = c.base04 },
		Normal = {
			bg = themeConfig.transparent and c.none or c.base01,
			fg = c.base10,
		},
		NormalFloat = {
			bg = themeConfig.transparent and c.none or c.base02,
			fg = c.base10,
		},
		-- NormalNC     { },
		Pmenu = { bg = c.base02, fg = c.base10 },
		PmenuSel = { bg = c.base03, fg = c.red400, bold = true },
		PmenuSbar = { bg = c.base04 },
		PmenuThumb = { bg = c.base05 },
		-- Question     { },
		-- QuickFixLine { },
		Search = { bg = c.yellow500, fg = c.base01 },
		-- SpecialKey   { },
		-- SpellBad     { },
		-- SpellCap     { },
		-- SpellLocal   { },
		-- SpellRare    { },
		-- StatusLine   { },
		-- StatusLineNC { },
		TabLine = { bg = c.base04, fg = c.base10 },
		TabLineFill = { bg = c.base04 },
		TabLineSel = { bg = c.base01, fg = c.base10, bold = true },
		Title = { fg = c.red500, bold = true },
		Visual = { bg = c.base04 },
		-- VisualNOS    { },
		-- WarningMsg   { },
		-- Whitespace   { },
		-- Winseparator { },
		-- WildMenu     { },
	}
end

return M
